### ISSUE TITLE
Readme instructions

### ISSUE THREAD

**Issue by irthomasthomas** [RedisGears/EdgeRealtimeVideoAnalytics#10]
In the readme the instructions for installing OpenCV say to go to this folder which I don't have. I only have folders here for python3.7

> Type cv2.__file__ - you should get something like '/usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so'
> Exit the python interpreter (CTRL-D)
> Go to /opt/redislabs/lib/modules/python27/.venv/lib/python2.7/site-packages
> Create a soft link like so: ln -s /usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so cv2.so

**Comment by itamarhaber** [comment]
Hello @irthomasthomas 

The README needs to be updated with the move to Python 3 and RedisGears' new-ish pipenv instructions, which makes everything easier I think. The gist of it - and please let me know if you encounter any issues - is:

1. Pull RedisGears v0.4 and make it
2. `sudo apt-get install python-opencv`
3. `cd /opt/redislabs/lib/modules/python3/`
4. `pipenv shell`
5. `pip install -r /path/to/the/repos/requirements.txt`
6. `exit`

That should be all that's needed.

**Comment by irthomasthomas** [comment]
Thank you @itamarhaber. It took me a little while but it's all running nice now. I'm obliged to you.
