### ISSUE TITLE
Change Tiny YOLO TO YOLO V3

### ISSUE THREAD

**Issue by Akhtar303** [RedisGears/EdgeRealtimeVideoAnalytics#11]
Hi @itamarhaber 
I want to change Tiny YOLO to YOLO v3  bcz of good performance ,I change code like that in **init.py**

with open(yolo.pb', 'rb') as f:
        model = f.read()
        res = conn.execute_command('AI.MODELSET', 'yolo:model', 'TF', args.device, 'INPUTS','input_1', 'input_image_shape', 'OUTPUTS','concat_11', 'concat_12', 'concat_13', model)

There is two input nodes ('INPUTS','input_1', 'input_image_shape') and OutPut Nodes 'concat_11', 'concat_12', 'concat_13' and also change **gears.py** like that 

redisAI.modelRunnerAddInput(modelRunner, 'input_1', image_tensor)
redisAI.modelRunnerAddOutput(modelRunner, 'concat_11', 'concat_12', 'concat_13')
 but it generate this error
ERROR: You must feed a value for placeholder tensor 'input_image_shape' with dtype float and shape [2]
	 [[{{node input_image_shape}}]]
Kindly tell me how to solve this problem.
Thanks

**Comment by itamarhaber** [comment]
You need to supply the image's shape tensor - have a look at this earlier commit for an implementation: https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/6a81ba2fdf69548b8ee9b26f0f39028460aca76b/app/gear.py#L57

**Comment by Akhtar303** [comment]
> You need to supply the image's shape tensor - have a look at this earlier commit for an implementation:
> 
> https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/6a81ba2fdf69548b8ee9b26f0f39028460aca76b/app/gear.py#L57

Thanks @itamarhaber for reply 
I am already do that like this ( modelRunner = redisAI.createModelRunner('yolo:model') .
This pipeline run smoothly when I am using Tiny YOLO but when change Tiny YOLO to YOLO V3 it create same problem.
Thanks

**Comment by itamarhaber** [comment]
Indeed - but do you also have the equivalent of line 59 in the above?

**Comment by Akhtar303** [comment]
> Indeed - but do you also have the equivalent of line 59 in the above?

my code is like that
modelRunner = redisAI.createModelRunner('yolo:model')
  redisAI.modelRunnerAddInput(modelRunner, 'input_1', image_tensor)
 redisAI.modelRunnerAddInput(modelRunner, 'input_image_shape', shape_tensor)
 redisAI.modelRunnerAddOutput(modelRunner, 'concat_11', 'concat_12', 'concat_13')
  model_replies = redisAI.modelRunnerRun(modelRunner)


    model_output = model_replies[0]

    prf.add('model')

**Comment by Akhtar303** [comment]
@itamarhaber 
I still face same problem my  init.py is like that
with open(yolo.pb', 'rb') as f:
model = f.read()
res = conn.execute_command('AI.MODELSET', 'yolo:model', 'TF', args.device, 'INPUTS','input_1', 'input_image_shape', 'OUTPUTS','concat_11', 'concat_12', 'concat_13', model)

**Comment by Akhtar303** [comment]
Hi @itamarhaber 
Have you run successfully  this Pipeine with **yolo_full_with_pipeline.pb** or which you mentioned above i.e
https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/6a81ba2fdf69548b8ee9b26f0f39028460aca76b/app/gear.py
I am exactly follow whole app code which you yo mentioned above for olo_full_with_pipeline.pb but I am unable to run successfully.
Thanks

**Comment by itamarhaber** [comment]
Yes, it definitely ran at a point with the full model.

**Comment by Akhtar303** [comment]
Thanks @itamarhaber for reply
I am completely follow your code with full model, it run successfully but don't perform any detections.
This line doesn't work -> shape_tensor = redisAI.createTensorFromValues('FLOAT', [2], [IMG_SIZE,IMG_SIZE])
https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/6a81ba2fdf69548b8ee9b26f0f39028460aca76b/app/gear.py#L54
after this line nothing has performed
i.e
This code don't go move forward after this line even print() statements doesn't work,it means all these line doesn't run
modelRunner = redisAI.createModelRunner('yolo:model')
    redisAI.modelRunnerAddInput(modelRunner, 'input_1', image_tensor)
    redisAI.modelRunnerAddInput(modelRunner, 'input_image_shape', shape_tensor)
    redisAI.modelRunnerAddOutput(modelRunner, 'concat_13')
    redisAI.modelRunnerAddOutput(modelRunner, 'concat_12')
    redisAI.modelRunnerAddOutput(modelRunner, 'concat_11')
    model_reply = redisAI.modelRunnerRun(modelRunner)
    # Get the model's outputs
    classes_tensor = model_reply[0]
kindly suggest me any solution for this problem.
Thanks

**Comment by Akhtar303** [comment]
Hi @itamarhaber 
I am struggling with same problem i.e not perform any detection with full YOLO but same pipe line work with Tiny YOLO  whole problem with this line  
https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/6a81ba2fdf69548b8ee9b26f0f39028460aca76b/app/gear.py#L54

This line doesn't run successfully , I also tried this line 
input_shape = rai.Tensor(rai.DType.float, shape=[2], value=[new_shape, new_shape])
con.tensorset('input_shape', input_shape)
but this line also didn't work for me.
There is no help on Internet kindly give me any direction or document to solve this problem ,I have consumed alot of Time.
Thanks
