### ISSUE TITLE
No box around the image is showing up in fully dockerized setup

### ISSUE THREAD

**Issue by karanveersingh5623** [RedisGears/EdgeRealtimeVideoAnalytics#17]
A processed frame with detection is not showing up in grafana and no metrics are showing up .
Let me know where is the issue .
Below is the screenshot for the same .

![Screen Shot 2020-02-05 at 11 19 55 AM](https://user-images.githubusercontent.com/30921663/73805253-7f8bdf00-4809-11ea-8830-841df0a8f6ac.png)

**Comment by karanveersingh5623** [comment]
Any update on this guys , is anything I am doing a wrong way

**Comment by itamarhaber** [comment]
Hello @karanveersingh5623 

We're looking into it.

**Comment by narfai** [comment]
Hello,

First of all thanks for that awesome demo !

It seems like RedisAI expect importing torch as implied for a pytorch scriptset and refuse to load the script because of that, giving that error :

```
redis.exceptions.ResponseError: expected def but found 'import' here: at <string>:1:0 import torch
```

I managed to get it working in full docker environment by removing the `import torch` in the file `app/yolo_boxes.py`.

**Comment by karanveersingh5623** [comment]
I am getting below error when removed import torch in the file yolo_boxes.py
`redis.exceptions.ResponseError: expected def but found 'import' here: at <string>:1:0 import torch ~~~~~~ <--- HERE  def nms(boxes):     # assuming only one image in one batch     boxes = boxes.squeeze()     nms_thresh = 0.45     conf_thresh = 0.2     no_of_valid_elems = (boxes[:, 4] > conf_thresh).nonzero().numel()     boxes_confs_inv = 1 - boxes[:, 4]     _, sort_ids = torch.sort(boxes_confs_inv)`

**Comment by karanveersingh5623** [comment]
`grafana_1                             | t=2020-02-11T07:02:33+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1                             | t=2020-02-11T07:02:33+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
init_1                                | Loading script - Traceback (most recent call last):
init_1                                |   File "init.py", line 42, in <module>
init_1                                |     res = conn.execute_command('AI.SCRIPTSET', 'yolo:script', args.device, script)
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
init_1                                |     return self.parse_response(connection, command_name, **options)
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
init_1                                |     response = connection.read_response()
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 642, in read_response
init_1                                |     raise response
init_1                                | redis.exceptions.ResponseError: expected def but found 'import' here: at <string>:1:0 import torch ~~~~~~ <--- HERE  def nms(boxes):     # assuming only one image in one batch     boxes = boxes.squeeze()     nms_thresh = 0.45     conf_thresh = 0.2     no_of_valid_elems = (boxes[:, 4] > conf_thresh).nonzero().numel()     boxes_confs_inv = 1 - boxes[:, 4]     _, sort_ids = torch.sort(boxes_confs_inv)
redisedge_1                           | 1:M 11 Feb 2020 07:02:32.866 * <rg> Initializing Python environment with: exec(open('/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py').read(), {'__file__': '/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py'})
`

**Comment by karanveersingh5623** [comment]
> grafana_1                             | t=2020-02-11T07:02:33+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1                             | t=2020-02-11T07:02:33+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
init_1                                | Loading script - Traceback (most recent call last):
init_1                                |   File "init.py", line 42, in <module>
init_1                                |     res = conn.execute_command('AI.SCRIPTSET', 'yolo:script', args.device, script)
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
init_1                                |     return self.parse_response(connection, command_name, **options)
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
init_1                                |     response = connection.read_response()
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 642, in read_response
init_1                                |     raise response
init_1                                | redis.exceptions.ResponseError: expected def but found 'import' here: at <string>:1:0 import torch ~~~~~~ <--- HERE  def nms(boxes):     # assuming only one image in one batch     boxes = boxes.squeeze()     nms_thresh = 0.45     conf_thresh = 0.2     no_of_valid_elems = (boxes[:, 4] > conf_thresh).nonzero().numel()     boxes_confs_inv = 1 - boxes[:, 4]     _, sort_ids = torch.sort(boxes_confs_inv)
redisedge_1                           | 1:M 11 Feb 2020 07:02:32.866 * <rg> Initializing Python environment with: exec(open('/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py').read(), {'__file__': '/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py'})

**Comment by narfai** [comment]
Did you should tried to re-build your docker images ?
`docker-compose up --build`

**Comment by karanveersingh5623** [comment]
@narfai  , I removed all the images and again gave docker-compose up , below is the output .
I guess something changed in FROM redislabs/redisedge:latest in redisedge folder .

`Jamess-Mac-Pro:EdgeRealtimeVideoAnalytics karanveer$ docker-compose up --build
Building redisedge
Step 1/8 : FROM redislabs/redisedge:latest
 ---> 1a0427006ffa
Step 2/8 : ENV DEPS "python python-pip libglib2.0-0 libsm6 libxrender1 libxext6 libgomp1"
 ---> Using cache
 ---> a84c619f22dd
Step 3/8 : RUN set -ex;     apt-get update;     apt-get install -y --no-install-recommends $DEPS;
 ---> Using cache
 ---> c10c0ee45cf6
Step 4/8 : RUN set -ex;     pip install pipenv;
 ---> Running in dda71671f692
+ pip install pipenv
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/bb/15/b155a5c0d19ce41609f50bb70a37e0de092b453ec4bd2eac59e53a2c3227/pipenv-2018.11.26-py2-none-any.whl (5.2MB)
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/ba/f8/50c2b7dbc99e05fce5e5b9d9a31f37c988c99acd4e8dedd720b7b8d4011d/virtualenv_clone-0.5.3-py2.py3-none-any.whl
Collecting certifi (from pipenv)
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
Collecting enum34; python_version < "3" (from pipenv)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting typing; python_version < "3.5" (from pipenv)
  Downloading https://files.pythonhosted.org/packages/22/30/64ca29543375759dc589ade14a6cd36382abf2bec17d67de8481bc9814d7/typing-3.7.4.1-py2-none-any.whl
Requirement already satisfied: pip>=9.0.1 in /usr/lib/python2.7/dist-packages (from pipenv) (18.1)
Collecting virtualenv (from pipenv)
  Downloading https://files.pythonhosted.org/packages/51/89/6f2827025b28eee6236b1905555b0fbe1749f27bcbd3732ee137c31a21a8/virtualenv-20.0.2-py2.py3-none-any.whl (4.6MB)
Collecting setuptools>=36.2.1 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl (583kB)
Collecting filelock<4,>=3.0.0 (from virtualenv->pipenv)
  Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-TvXd22/filelock/
ERROR: Service 'redisedge' failed to build: The command '/bin/sh -c set -ex;     pip install pipenv;' returned a non-zero code: 1`

**Comment by karanveersingh5623** [comment]
@narfai , got it working , below is the dockerfile we need to change to 

`FROM redislabs/redisedge:latest
  
ENV DEPS "python python3-pip libglib2.0-0 libsm6 libxrender1 libxext6 libgomp1"
RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends $DEPS;

RUN pip3 install -U setuptools
RUN set -ex; \
    pip3 install pipenv;

ADD ./requirements.txt /tmp/requirements.txt
RUN set -ex; \
    cd /opt/redislabs/lib/modules/python3; \
    pipenv run pip3 install -r /tmp/requirements.txt;

ADD ./redisedge.conf /usr/local/etc/redisedge.conf

CMD ["/usr/local/etc/redisedge.conf"]`

**Comment by itamarhaber** [comment]
Thanks @karanveersingh5623 & @narfai for the help.

I've put #18 to resolve this (and fix another issue along the way). Should be better now.
