### ISSUE TITLE
'Invalid GraphDef' on starting 'init' leads to 404 for 'server'

### ISSUE THREAD

**Issue by skini-galaxia** [RedisGears/EdgeRealtimeVideoAnalytics#45]
**Starting the 'init' service raises the following error. This causes a 404 on the 'server'.**

```
edgerealtimevideoanalytics_redisedge_1 is up-to-date
Starting edgerealtimevideoanalytics_init_1 ... done
Attaching to edgerealtimevideoanalytics_init_1
init_1                                | Loading model - Traceback (most recent call last):
init_1                                |   File "init.py", line 35, in <module>
init_1                                |     res = conn.execute_command('AI.MODELSET', 'yolo:model', 'TF', args.device, 'INPUTS', 'input', 'OUTPUTS', 'output', model)
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
init_1                                |     return self.parse_response(connection, command_name, **options)
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
init_1                                |     response = connection.read_response()
init_1                                |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 642, in read_response
init_1                                |     raise response
init_1                                | redis.exceptions.ResponseError: Invalid GraphDef
edgerealtimevideoanalytics_init_1 exited with code 1

```

**Comment by DvirDukhan** [comment]
hi @skini-galaxia 
can you verify the model file is there? you need to execute `git lfs install; git lfs fetch; git lfs checkout`

**Comment by skini-galaxia** [comment]
hi @DvirDukhan , thanks for the reply. I can see a models dir. in the app dir. Where do i execute these git commands?

**Comment by DvirDukhan** [comment]
@skini-galaxia in the repository root folder

**Comment by skini-galaxia** [comment]
@DvirDukhan unfortunately the issue still persists after running the commands.

**Comment by skini-galaxia** [comment]
@DvirDukhan i can only see one file in /app/models. That is tiny-yolo-voc.pb.

**Comment by skini-galaxia** [comment]
@DvirDukhan the issue is fixed after running the git commands and doing a build. However the 'server' is still throwing a 404.
debug=True is not giving any proper logs.
On hitting http://0.0.0.0:5000/, I am getting this,
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by DvirDukhan** [comment]
hi
I belive the correct address is as written in the docs:

The application's rendered video stream (server.py) should be at http://localhost:5000/video.
The Docker Compose setup also comes with a pre-provisioned Grafana server - it should be at http://localhost:3000/ (admin/admin).

can you please verify?

**Comment by skini-galaxia** [comment]
@DvirDukhan the only content I can see on  http://localhost:5000/video is the example gif, is this correct? I cannot see any other metrics/UI. The grafana server works perfectly. Thanks

**Comment by skini-galaxia** [comment]
@DvirDukhan i am able to view the dashboard now. However as mentioned in one of the issues, i would suggest changing 
opencv-python>=4.0.1.23 to opencv-python==4.0.1.23 to in app/requirements.txt

**Comment by DvirDukhan** [comment]
ok
thanks
