### ISSUE TITLE
Question, why py2 and py3? 

### ISSUE THREAD

**Issue by robmarkcole** [RedisGears/EdgeRealtimeVideoAnalytics#5]
Hi chaps
sorry for raising this question as an issue, but I am curious to know why you are mixing python 2.7 and python 3 - is it a requirement flowing from Redis?

**Comment by itamarhaber** [comment]
Hello @robmarkcole 

Nope, all should be Python 3, would you kindly point me to where Python 2 remained?

**Comment by robmarkcole** [comment]
Sorry I meant to create the issue on https://github.com/RedisGears/AnimalRecognitionDemo/tree/master/camera
Had both repo up at the time!

**Comment by itamarhaber** [comment]
lol - ok, so feel free to close this and open there.

**Comment by haiyang-tju** [comment]
Why the host must have OpenCV for Python2.7, described on Readme file?
