### ISSUE TITLE
How to call module redisAI and class GearsBuilder?

### ISSUE THREAD

**Issue by haiyang-tju** [RedisGears/EdgeRealtimeVideoAnalytics#7]
In file `./app/gear.py`, lines [3](https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/master/app/gear.py#L3) and [222](https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/master/app/gear.py#L222):

```
import redisAI

***

gb = GearsBuilder('StreamReader')
```
I executed this `exec(open('/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py').read(), {'__file__': '/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py'})` in python, and 
I got the errors as follows:

`ModuleNotFoundError: No module named 'redisAI'` and `NameError: name 'GearsBuilder' is not defined`.

Indeed, I searched for the definition of GearsBuilder CLASS in `https://github.com/RedisGears/RedisGears/blob/master/src/GearsBuilder.py`.

Did I miss something? How to call module redisAI and class GearsBuilder?

THANKS.

**Comment by haiyang-tju** [comment]
AND, the redis-server outputs goes there:
```
8424:M 30 Jul 2019 16:25:34.495 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
8424:M 30 Jul 2019 16:25:34.495 # Server initialized
8424:M 30 Jul 2019 16:25:34.495 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
8424:M 30 Jul 2019 16:25:34.495 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
8424:M 30 Jul 2019 16:25:34.952 * Module 'ai' loaded from ../RedisAI/build/redisai.so
8424:M 30 Jul 2019 16:25:34.978 * <rg> RedisGears version 99.99.99, git_sha=820f1808fb1c5f8cae809ecef717cfe950fb1102
8424:M 30 Jul 2019 16:25:34.978 * <rg> PythonHomeDir:/opt/redislabs/lib/modules/python3/
8424:M 30 Jul 2019 16:25:34.978 * <rg> MaxExecutions:1000
8424:M 30 Jul 2019 16:25:34.978 * <rg> ProfileExecutions:0
8424:M 30 Jul 2019 16:25:34.978 * <rg> PythonAttemptTraceback:1
8424:M 30 Jul 2019 16:25:34.978 * <rg> RedisAI api loaded successfully.
could not initialize RediSearch_CheckApiVersionCompatibility
8424:M 30 Jul 2019 16:25:34.978 # <rg> could not initialize RediSearch api, running without Search support.
8424:M 30 Jul 2019 16:25:35.100 * <rg> Initializing Python environment with: exec(open('/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py').read(), {'__file__': '/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py'})
8424:M 30 Jul 2019 16:25:35.544 * Module 'rg' loaded from ../RedisGears/redisgears.so
8424:M 30 Jul 2019 16:25:35.546 * DB loaded from disk: 0.002 seconds
8424:M 30 Jul 2019 16:25:35.546 * Ready to accept connections

```

**Comment by MeirShpilraien** [comment]
Why you tried to activate the virtual env via the gears script? It should have already been activated by gears.

**Comment by haiyang-tju** [comment]
Thanks for your reply! @MeirShpilraien

You means that the virtual environment is already activated as soon as the module is loaded by `redis-server` ?  I can't execute the python file `./app/gear.py`,  so I activate the virtual env by hand, and it still can't runs.
```
import redisAI
>>ModuleNotFoundError: No module named 'redisAI'

gb = GearsBuilder('StreamReader')
>>NameError: name 'GearsBuilder' is not defined.
```

My redis-server outputs says the modules of AI and Gears have been loaded successfully. Why is this happening?

**Comment by MeirShpilraien** [comment]
Are you using the docker or you compiled redisgears yourself? If you compiled yourself which version? And just to make sure you are running the script using RG.PYEXECUTE right?

**Comment by haiyang-tju** [comment]
I compiled it by myself and the version is 99.99.99(I just git clone from master branch).

The command `RG.PYEXECUTE` in redis-cli is ok. I am more confused about is how to execute a python script directly. 

Or Is it can only be executed in redis-cli? Some example in [there](https://dzone.com/articles/introduction-to-redis-gears) say it seems to be like this.

**Comment by MeirShpilraien** [comment]
Can you put the logs of the redis server here?

**Comment by MeirShpilraien** [comment]
Ohh you already put it, I missed it.

**Comment by MeirShpilraien** [comment]
Let me check that there is no regression in gears current master. Will get back to you.

**Comment by MeirShpilraien** [comment]
@haiyang-tju I just compiled from RedisGears current master and it looks like its working:
```
127.0.0.1:6379> RG.PYEXECUTE "import redisAI"
OK
127.0.0.1:6379> RG.PYEXECUTE "print(GearsBuilder)"
OK
127.0.0.1:6379>
```
Maybe something in the compilation went wrong, is it possible to somehow pass the compilation output?

**Comment by haiyang-tju** [comment]
Thanks for your kind reply! @MeirShpilraien  

I understand how it works now. I am wondering why it can't work in my local python environment, and it is so weird by running python code in redis-cli.

And then there is no problem for the code. Thanks again, thanks for your team of this interesting work.

**Comment by MeirShpilraien** [comment]
@haiyang-tju the idea is that the python code will run on redis where the data is.
You can take a look at this library which allows you to run it remotly:
https://github.com/RedisGears/redisgears-py
